### ISSUE TITLE
Is there a way to disable whatever LanguageServer does at startup ?

### ISSUE THREAD

**Issue by jonathanBieler** [julia-vscode/LanguageServer.jl#363]
When I launch vs-code it starts several Julia processes that uses 100% cpu for ever (I eventually get some error message in vs-code). It looks like it's loading packages or something like this.

Is there a way to disable this (or kill it for good) ? I have to disable the extension because of it, and I just want syntax highlighting.

**Comment by davidanthoff** [comment]
No, unfortunately not... I think if you let it run through this initial phase once, though, it should (at least in theory) not do it again (it is caching a lot of stuff).

If you could post the error message, it would be great!

It would be neat if we could lower the priority of that client process, though, so that it at least doesn't interfere so much with other things you might be doing on your machine.

**Comment by jonathanBieler** [comment]
It eventually settled down, what is it doing that takes so long ? Just curious.

**Comment by ZacLN** [comment]
It loads and caches every package installed in your env. It should then only reload those that change.

**Comment by jonathanBieler** [comment]
Ok, no wonder it takes so long. At the end I commented out the part that [starts](https://github.com/julia-vscode/julia-vscode/blob/master/scripts/languageserver/main.jl#L22) the server, so I just get syntax highlighting.
