### ISSUE TITLE
Log debug messages with @debug instead of with server.debug_mode && @info

### ISSUE THREAD

**Issue by non-Jedi** [julia-vscode/LanguageServer.jl#421]
The `debug_mode` field of `LanguageServerInstance` should be eliminated. Instead, all debug output that's currently gated with `server.debug_mode && @info "debug log"` should simply be `@debug "debug log"`. This way, logging can be controlled with the standard tools from the `Logging` library instead of having to be aware of the `debug_mode` field.

I think this is better than eliminating logging as in #266 as it can be useful for debugging other clients even if unneeded for vscode.

Obviously, this is a rather simple set of PRs to LanguageServer and SymbolServer, but I wanted to make sure there was support for this before doing the work. This would also be a breaking change and so would probably require a version bump to 2.0...

**Comment by davidanthoff** [comment]
Yes, agreed, that would be better. We would just have to adjust [this](https://github.com/julia-vscode/julia-vscode/blob/master/scripts/languageserver/main.jl#L15) as well so that we still get that debug output when the VS Code extension is run in debug mode. But I think that should be fairly straightforward.
