### ISSUE TITLE
Broken completion when triggered inside parentheses, brackets or braces in coc.nvim.

### ISSUE THREAD

**Issue by lassepe** [julia-vscode/LanguageServer.jl#447]
When triggering completion within `()`, `{}` or `[]` (e.g. when completing a function call like `identity(<trigger-completion>)`) any completion that comes from the Julia language server source is inserted incorrectly. Instead of closing the bracket after the auto-completed word, the bracket appears after the last letter of the fragment that I typed before triggering completion:

E.g. here I typed `so<trigger-completion>` inside `identity(.)` and as you can see from the screenshot, the `s` is missing, a `)` is inserted after the last character of the fragment I typed, followed by the rest of the word and an additional `)` at the end.

![image](https://user-images.githubusercontent.com/10076790/71217727-89ff1300-2273-11ea-914d-16fe4944415e.png)

I am not sure whether this is the right place to post this issue as I don't really know how to debug this problem. However, I have not observed this behavior within my `cpp` setup and it does not occur in my  Julia setup when completing from the buffer world list: 

![image](https://user-images.githubusercontent.com/10076790/71217896-448f1580-2274-11ea-8dec-0ceff4c9660b.png)

**Comment by kdheepak** [comment]
For what it's worth, I also have the same issue.

**Comment by lassepe** [comment]
@kdheepak have been successful in running `LanguangeServer.jl` with any `coc.nvim` alternatives?

**Comment by kdheepak** [comment]
Yes! I was able to run it most successfully with [autozimu/LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim/). However, even then I had other issues such as infinite recursive caching + lag + inconsistent or odd tab completion behaviour when in a Julia file in vim, and I didn't encounter any issues in other languages (Python / Javascript). I've also tried it with neovim nightly which has a built in LSP client, and had a different set of issues that may be unrelated to LanguageServer.jl, although I didn't have any issues with NVIM LSP and Python / vimscript. 

I've currently just disabled LanguageServer for julia because I needed to get actual work done :) I'll revisit when I get the chance.

**Comment by lassepe** [comment]
Maybe an important data point to this end: This only happens if I select the entry using the `<tab>` key. If I use arrow-keys to make a selection, things seem to work fine.

**Comment by pfitzseb** [comment]
That sounds like it's purely a client issue then, no?

**Comment by kdheepak** [comment]
For what it is worth, I don't have this issue when using [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig). So it must be something that coc.nvim / coc-julia is doing with the information it receives from LanguageServer.jl.

That said, this might also be related to https://github.com/julia-vscode/LanguageServer.jl/issues/747.

**Comment by pfitzseb** [comment]
That issue should be fixed now, no?

**Comment by lassepe** [comment]
I'd like to verify this for you but due to #835 it's hard for me to reproduce. The only way I can get `LanguageServer.jl` to work (still with this bug) is through [coc-julia](https://github.com/fannheyward/coc-julia) but I'm not sure whether they applied this fix; @fannheyward?

**Comment by fannheyward** [comment]
> whether they applied this fix

Yes, coc-julia bundled the latest LS.jl with this patch
