### ISSUE TITLE
 Variable completion candidates always show the type Enum

### ISSUE THREAD

**Issue by dmalyuta** [julia-vscode/LanguageServer.jl#872]
I'm using Emacs, but I think this is a `LanguageServer.jl` issue (see my first attempt at https://github.com/non-Jedi/lsp-julia/issues/43). First of all, I am using:

- Emacs: GNU Emacs 27.1.90
- OS: Ubuntu 20.04.1 LTS
- Julia: 1.5.3
- LanguageServer.jl: [2b0e0bc5] LanguageServer v3.2.1-DEV `https://github.com/julia-vscode/LanguageServer.jl#master`
- SymbolServer.jl: [cf896787] SymbolServer v6.0.1

The issue that I'm seeing is that while variable completion candidates show up (for structs, workspace variables, etc.), they are always labelled as having the type "Enum". But I have specified the variable type, as you can see in the example below, so I feel like it should be possible for LSP to retrieve and show that information? Any help is very much appreciated on this matter, because it is annoying to have to jump to the variable definition in order to check its type.

![image](https://user-images.githubusercontent.com/12475811/106040500-6968d580-608f-11eb-81cf-a05c1ad12c10.png)

In VSCode, the variable types are not shown directly either. Instead, there is a mini-window where one can preview the line on which the variable is defined, where the type becomes visible. However, I believe that this is simply a GUI facility. It would be nice if LanguageServer directly provided the variable's type.

![image](https://user-images.githubusercontent.com/12475811/106196524-5ffe6c80-6166-11eb-94a9-ecd779438020.png)

**Comment by fredrikekre** [comment]
I tried to debug this issue and my conclusion is that https://github.com/julia-vscode/LanguageServer.jl/blob/37068f00a85d6889af3506daab3554aed008aa0d/src/requests/completions.jl#L284-L310 is incorrect in more ways than just for this case. In paritcular, local variables and function arguments both end up at https://github.com/julia-vscode/LanguageServer.jl/blob/37068f00a85d6889af3506daab3554aed008aa0d/src/requests/completions.jl#L297 (which is why they show as `Enum`). I don't know `StaticLint` enough to go further here I think.

```diff
diff --git a/src/requests/completions.jl b/src/requests/completions.jl
index cbd7b46..578fa55 100644
--- a/src/requests/completions.jl
+++ b/src/requests/completions.jl
@@ -293,6 +293,8 @@ function _completion_kind(b)
             return 12
         elseif b.type == StaticLint.CoreTypes.DataType
             return 22
+        elseif b.type === nothing || b.type isa SymbolServer.DataTypeStore
+            return 6
         else
             return 13
         end
```
"fixes" both local variables and function arguments to show up as variables instead, but I have no idea if this is correct.

**Comment by pfitzseb** [comment]
Yeah, that looks correct to me.

**Comment by fredrikekre** [comment]
Okay, I pushed that commit to https://github.com/julia-vscode/LanguageServer.jl/pull/1051.

**Comment by fredrikekre** [comment]
Ah, the original issue was with struct members, but that is also fixed by the referenced commit:
![Screenshot from 2022-04-08 15-05-09](https://user-images.githubusercontent.com/11698744/162441546-2514c7cd-aa45-437a-ad40-932add399581.png)
![Screenshot from 2022-04-08 15-05-23](https://user-images.githubusercontent.com/11698744/162441564-692a2b5f-5e3a-4283-b9b7-6082dd5586fb.png)
However, maybe it should actually be https://github.com/julia-vscode/LanguageServer.jl/blob/37068f00a85d6889af3506daab3554aed008aa0d/src/protocol/completion.jl#L6 or https://github.com/julia-vscode/LanguageServer.jl/blob/37068f00a85d6889af3506daab3554aed008aa0d/src/protocol/completion.jl#L11.

**Comment by pfitzseb** [comment]
We definitely know what type the completion has. Might be a bit tricky to surface that info though.

**Comment by fredrikekre** [comment]
Yea, but perhaps not with the information that is currently sent to `_completion_kind`? At the `_completion_kind` callsite it should be easier.

**Comment by pfitzseb** [comment]
`b.type` for `foo.x\tab` in this example is
```
SymbolServer.DataTypeStore(
    SymbolServer.FakeTypeName(
        SymbolServer.VarRef(
            SymbolServer.VarRef(nothing, :Core), :Int64
        ), Any[]
    ), 
    SymbolServer.FakeTypeName(
        SymbolServer.VarRef(
            SymbolServer.VarRef(nothing, :Core), :Signed
        ), Any[]
    ), 
    Any[], 
    Any[], 
    Any[], 
    SymbolServer.MethodStore[], "", true
)
```
so yes, we do have the info. Just a bit tricky to get the right abstract type out of that (adding a `detail` with the typename seems easy).

**Comment by pfitzseb** [comment]
https://github.com/julia-vscode/LanguageServer.jl/pull/1052.
