### ISSUE TITLE
Tag a Release?

### ISSUE THREAD

**Issue by lassepe** [julia-vscode/LanguageServer.jl#998]
Recently, a lot of great features have made it into LanguagesServer.jl. In particular, the switch to JuliaFormatter.jl. It may be nice to tag a release for these changes.

**Comment by pfitzseb** [comment]
Yeah, sure. I'll try to get this done by tomorrow.

**Comment by clason** [comment]
Just to make sure (not trying to hurry you!): Are you going to tag a release of the stand-alone `LanguageServer.jl` as well? (Not everybody uses VS Code ;))

**Comment by pfitzseb** [comment]
Yes. Tomorrow maybe? :)

**Comment by gdkrmr** [comment]
Tagging a new version would help out emacs lsp-mode!

**Comment by non-Jedi** [comment]
@pfitzseb since I have commit rights, any objection to me doing a round of tagging? I'm assuming the procedure is the same as seen at https://github.com/julia-vscode/LanguageServer.jl/commit/b855f1310d2fe7cbd03b15e23731756703353a7a.

Repos to tag would be:
- https://github.com/julia-vscode/LanguageServer.jl
- https://github.com/julia-vscode/CSTParser.jl
- https://github.com/julia-vscode/StaticLint.jl
- https://github.com/julia-vscode/SymbolServer.jl
- https://github.com/julia-vscode/JSONRPC.jl

Any breaking changes you're aware of requiring a major version bump?

**Comment by non-Jedi** [comment]
I'll leave those PRs open for a day or two, and then if nobody yells at me, I'll try to trigger @JuliaRegistrator.

**Comment by pfitzseb** [comment]
CSTParser doesn't technically need a tag, although 3.3 wasn't tagged correctly -- should've been 4.0 instead. I've approved your PRs, so merge and tag a release whenever :)
